package com.pccube.espd.enums;

public enum ResponseData {

	AMOUNT("AMOUNT"),
	CODE("CODE"),
	CODE_COUNTRY("CODE_COUNTRY"),
	DATE("DATE"),
	DESCRIPTION("DESCRIPTION"),
	EVIDENCE_IDENTIFIER("EVIDENCE_IDENTIFIER"),
	INDICATOR("INDICATOR"),
	PERCENTAGE("PERCENTAGE"),
	PERIOD("PERIOD"),
	QUANTITY_INTEGER("QUANTITY_INTEGER"),
	QUANTITY_YEAR("QUANTITY_YEAR"),
	QUANTITY("QUANTITY"),
	NONE("NONE"),
	IDENTIFIER("IDENTIFIER"),
	URL("URL"),
	MAXIMUM_AMOUNT("MAXIMUM_AMOUNT"),
	MINIMUM_AMOUNT("MINIMUM_AMOUNT"),
	MAXIMUM_VALUE_NUMERIC("MAXIMUM_VALUE_NUMERIC"),
	MINIMUM_VALUE_NUMERIC("MINIMUM_VALUE_NUMERIC"),
	TRANSLATION_TYPE_CODE("TRANSLATION_TYPE_CODE"),
	CERTIFICATION_LEVEL_DESCRIPTION("CERTIFICATION_LEVEL_DESCRIPTION"),
	COPY_QUALITY_TYPE_CODE("COPY_QUALITY_TYPE_CODE"),
	TIME("TIME"),
	LOT_IDENTIFIER("LOT_IDENTIFIER"),
	WEIGHT_INDICATOR("WEIGHT_INDICATOR"),
	CODE_BOOLEAN("CODE_BOOLEAN"),
	ECONOMIC_OPERATOR_IDENTIFIER("ECONOMIC_OPERATOR_IDENTIFIER");


	private final String code;

	ResponseData(String code) {
		this.code = code;
	}

	public String getCode() {
		return code;
	}
}
